### PR TITLE
Fix error when routing with array containing symbol.

### LINKED ISSUE #5869: NameError error was raised: undefined local variable or method 'parent' for...
### Expected behavior

Can redirect to route generated from array with symbols.

### Actual behavior

`NameError error was raised: undefined local variable or method 'parent' for #<Admin::PostsController:0x00005651fc262588`

### How to reproduce

Try doing `redirect_to [:admin, post]` in a active admin controller.

### PR DESCRIPTION
**Pull request by JWesorick**
See spec to reproduce issue. 

Looks like this was introduced in https://github.com/activeadmin/activeadmin/commit/d12dc9ab9ee8dd497fd29511961604aadf9b5f68#diff-9fd0a96ab1d1ed0f5d9e1258260e1cef

Fixes #5869

### CODE REVIEW

**Comment by JWesorick** [comment]
@deivid-rodriguez I think this is ready to merge. The one failing spec looks like it just timed out.

**Comment by JWesorick** [comment]
@deivid-rodriguez I think this is ready but something is up with the checks. They just never finished.

**Comment by javierjulio** [comment]
@JWesorick I believe @deivid-rodriguez fixed the issue in #5883. We just merged that in. Can you please rebase again and push? That should hopefully fix the CI build. Thanks! ❤️

**Comment by deivid-rodriguez** [comment]
Yes, I think it should be all good now.
