### ISSUE TITLE
jquery ui sortable does not work anymore

### ISSUE THREAD

**Issue by haraldkrischner** [activeadmin/activeadmin#5315]
I am on AA 1.2.1, I updated from 1.0.0. I have jquery-ui-rails installed from another dependency…

### Expected behavior
I should be able to use jquery uis sortable, as it worked in 1.0.0

### Actual behavior
JS-Error: `this._addClass is not a function`
`this` seems to be undefined throughout the widget. I tried it with sole jquery 3.2.1 and jquery ui 1.2.1 and had no problem. 

### How to reproduce
`$( "table tbody" ).sortable()`

**Comment by varyonic** [comment]
@javierjulio ?

**Comment by javierjulio** [comment]
I don't know. I'd need more info to go off of. Do you have a sample app to demonstrate the issue? It would help us understand if its a problem with ActiveAdmin or a possible collision with a dependency. What do you mean you tried it with jquery/jquery ui? We include the jQuery UI code directly in the ActiveAdmin gem.

**Comment by haraldkrischner** [comment]
Thanks for your attention, you may close this issue as I substituted the gem needing jquery-ui-rails (in version 5.0.5). Then sortable worked again, it seemed to include the wrong jquery-ui code. Maybe the AA gem could ensure using the code from it's vendor directory.
