### ISSUE TITLE
Zeitwerk autoloading deprecation on Rails 6.0.0.pre1

### ISSUE THREAD

**Issue by ryanwood** [activeadmin/activeadmin#5772]
### Expected behavior

Upon upgrading a Rails 5.2.3 app to Rails 6.0.0.pre1 and regenerating the ActiveAdmin initializer, I expect to see no deprecation warnings.

### Actual behavior

When running `rspec` (v3.8) on Rails 6.0.0.pre1 and Ruby 2.5.5 I get the following deprecation warning from [Zeitwerk](https://github.com/fxn/zeitwerk) the new default autoloader in Rails 6:

```
DEPRECATION WARNING: Initialization autoloaded the constants ApplicationHelper, ActiveAdmin::ViewsHelper, [...snip lots of other classes...], InheritedResources::Base, Base, DeviseController, Devise::SessionsController, Devise::PasswordsController, Devise::UnlocksController, Devise::RegistrationsController, and Devise::ConfirmationsController.

Being able to do this is deprecated. Autoloading during initialization is going
to be an error condition in future versions of Rails.

Reloading does not reboot the application, and therefore code executed during
initialization does not run again. So, if you reload ApplicationHelper, for example,
the expected changes won't be reflected in that stale Module object.

These autoloaded constants have been unloaded.

Please, check the "Autoloading and Reloading Constants" guide for solutions.
```
When I comment out the ActiveAdmin initializer, there is no deprecation warning. 

### How to reproduce

Run `rspec` (v3.8), or anything that will output deprecations, on Rails 6.0.0.pre1 and Ruby 2.5.5.

**Comment by deivid-rodriguez** [comment]
Hello @ryanwood! :wave:

I've actually been reported the same thing privately, but I thought it was only happening against Rails master (6.1.0.alpha). Does this also happen with `rails 6.0.0.rc1` and `ruby 2.6.3`? Can you share a sample application that reproduces this?

Thank you!

**Comment by pomartel** [comment]
I'm also having this issue. After some debugging, I see it happens only if I add a `before_filter` in the config file:
```
config.before_action :ensure_application_is_installed
```

I tried including this as a module instead like this:
```
ActiveAdmin::BaseController.include(ActiveAdmin::AdminAuthorization)
```

But this too triggers the deprecation warning. Not sure if this important, everything works fine but I guess it could cause some issues along the way with the next versions of Rails.

**Comment by Lukom** [comment]
@pomartel you can move logic of your `before_action` to `config.authentication_method` method, eg.

Before:
```ruby
config.authentication_method = :require_admin
config.before_action :ensure_application_is_installed
```
After:
```ruby
config.authentication_method = :require_admin_and_ensure_stuff
```
It'll work in the same way because authentication_method is called ad the beginning of each request anyway.
Of course, it's not perfect solution, it'd be great for ActiveAdmin gem to fix the issue, though it fixes the warning for now.

**Comment by pomartel** [comment]
@Lukom Thanks, that does the trick! 🙏

**Comment by thisismydesign** [comment]
Any trick for when I want to do `skip_before_action`?

**Comment by gingerlime** [comment]
@deivid-rodriguez any plans to look into this? it still happens with latest rails 6.0.2.1 when there are `before_action` or `skip_before_action` used... I'm seeing similar deprecation warnings for devise as reported initially.

**Comment by sunny** [comment]
Another trick to do allow both `before_action` and `skip_before_action` is to include them in your application controller, but with a condition:

```rb
before_action :do_something, if: :active_admin?

skip_before_action :do_something_else, if: :active_admin?

private

def active_admin?
  request.controller_class.module_parents.include?(Admin)
end
```

**Comment by deivid-rodriguez** [comment]
Sorry @gingerlime that I never got to answer this. Not sure when I'll get to it, too much on my plate at the moment, sorry.

**Comment by gingerlime** [comment]
Thanks @deivid-rodriguez. No worries. We managed to work around it for now :)

**Comment by Ecco** [comment]
Got hit by this too. The workaround works! That being said, it seems a bit sub-optimal since every request will have to check if `active_admin?` is true. I think it'd be great to fix this at some point 😄

**Comment by jeantristan** [comment]
For the record, I was also hit by the problem.
The problem was tied to ActiveAdmin and FriendlyId.
Removing this portion of code did the job:
```
  ActiveAdmin::ResourceController.class_eval do
    def find_resource
      resource_class.is_a?(FriendlyId) ? scoped_collection.friendly.find(params[:id]) : scoped_collection.find(params[:id])
    end
  end
```

**Comment by dorianmariefr** [comment]
thanks @jeantristan i had the exact same issue, the monkey patch needs to be in an `on_load` like this:

```
ActiveSupport.on_load(:active_admin) do
  ActiveAdmin::ResourceController.class_eval do
    def find_resource
      if resource_class.is_a?(FriendlyId)
        scoped_collection.friendly.find(params[:id])
      else
        scoped_collection.find(params[:id])
      end
    end
  end
end
```

**Comment by JohnPettigrew** [comment]
@dorianmariefr That was it - wrapping the friendly_id compatibility tweak in an `on_load` finally stopped this warning popping up all the time, which has been happening since 6.0.0 through to current 6.0.3. Thanks!

**Comment by tomgilligan** [comment]
i was having the same problem with `prepend_before_action` / `before_action` / `around_action` etc.  moving calls from the `_action` methods on `config` to an `on_load` block at the bottom of the file worked for me.

for example, instead of this:

```
ActiveAdmin.setup do |config|
  config.prepend_before_action -> { Time.zone = "Melbourne" }
end
```

this:

```
ActiveAdmin.setup do |config|
end

ActiveSupport.on_load(:active_admin) do
  ActiveAdmin::BaseController.class_eval do
    prepend_before_action -> { Time.zone = "Melbourne" }
  end
end
```

**Comment by mhenrixon** [comment]
```ruby
config.namespace :backoffice do |ns_config|
    ns_config.authorization_adapter   = AdminAuthorization
```

This also breaks it and I don't see a good way of solving it

**Comment by teenu4** [comment]
> ```ruby
> config.namespace :backoffice do |ns_config|
>     ns_config.authorization_adapter   = AdminAuthorization
> end
> ```
> 
> This also breaks it and I don't see a good way of solving it

try to use string instead of class, solved the issue for me.

```ruby
config.namespace :backoffice do |ns_config|
    ns_config.authorization_adapter   = 'AdminAuthorization'
end
 ```

**Comment by jensljungblad** [comment]
`ActiveSupport.on_load(:active_admin) do` doesn't seem to work for me. Is it supposed to?

**Comment by docstun** [comment]
I experienced the same problem but using `ActiveAdmin.after_load` seems to work around this in ActiveAdmin 2.9.0. 

So in our initializer we now do:

    ActiveAdmin.setup do |config|
      ...
    end

    ActiveAdmin.after_load do
      ActiveAdmin::BaseController.class_eval do
        skip_before_action :some_method
        ...
      end
    end

I no longer see any deprecation warning and the behaviour still seems to work fine.

**Comment by LarsDK** [comment]
This worked for me with active admin 2.7.0, thanks

**Comment by LarsDK** [comment]
@tomgilligan 
ActiveAdmin.setup do |config|
end

ActiveSupport.on_load(:active_admin) do
  ActiveAdmin::BaseController.class_eval do
    prepend_before_action -> { Time.zone = "Melbourne" }
  end
end

worked for me with activeadmin 2.7.0, thanks

**Comment by TheUrbina20** [comment]
In my case we where using an `active_admin_device.rb` initializer where we referenced some controller.
Wrap config inside `ActiveAdmin.after_load` did the trick.

**Comment by Envek** [comment]
One more broken use case because of this:

I tried to use [Action Policy](https://actionpolicy.evilmartians.io/) which has [automatic integration into Rails application's controllers](https://github.com/palkan/action_policy/blob/4dc3b1e412b10f18cd91f39308a49a3c404c443b/lib/action_policy/railtie.rb#L83-L88).

However, the problem is that this code in Active Admin initializer:
```ruby
ActiveAdmin.setup do |config|
  config.skip_before_action :some_method
end
```
references application controller **before application initialization process is finished** and forces its autoload and executing of its code, including calls to Action Policy methods, defined in not yet imported module. And everything breaks with `undefined method 'authorize'`.

Workarounds:

 1. Either include Action Policy module explicitly:

    ```ruby
    class ApplicationController < ActionController::Base
      include ActionPolicy::Controller
      authorize :guest, through: :current_guest
    end
    ```

 2. Or use `ActiveAdmin.after_load` in Active Admin initializer:

    ```ruby
    ActiveAdmin.after_load do
      ActiveAdmin::BaseController.class_eval do
        skip_before_action :some_method
      end
    end
    ```

**Comment by nasa42** [comment]
Following works on Rails 6.1+

```ruby
# config/initializers/active_admin.rb

ActiveAdmin.setup do |config|
  # other configs

  Rails.application.reloader.to_prepare do
    config.before_action :name_of_the_before_action
  end

  # more configs
end
```

**Comment by anna-eko** [comment]
> In my case we were using an `active_admin_device.rb` initializer where we referenced some controller. Wrap config inside `ActiveAdmin.after_load` did the trick.

this totally solved my problem of zeitwerk error when upgrading to Rails 7 with our customized controller. Otherwise it will keep complaining about devise basically not loaded.
