### ISSUE TITLE
Integration with CanCan failing with new 0.5.0+ version

### ISSUE THREAD

**Issue by toptierlabs** [activeadmin/activeadmin#1671]
It worked on 0.4.x.

I get the following error when entering the dashboard:

```
Rendered /Users/toptier/.rvm/gems/ruby-1.9.2-p320/bundler/gems/active_admin-3d6976ccf8a4/app/views/active_admin/page/index.html.arb (26.0ms)
Completed 500 Internal Server Error in 190ms

ActionView::Template::Error (undefined local variable or method `current_user' for #<Admin::DashboardController:0x007fdd2c0a9c20>):
    1: insert_tag active_admin_application.view_factory["page"]
  app/admin/admin_users.rb:3:in `block (2 levels) in <top (required)>'

Rendered /Users/toptier/.rvm/gems/ruby-1.9.2-p320/gems/actionpack-3.1.8/lib/action_dispatch/middleware/templates/rescues/_trace.erb (1.7ms)
Rendered /Users/toptier/.rvm/gems/ruby-1.9.2-p320/gems/actionpack-3.1.8/lib/action_dispatch/middleware/templates/rescues/_request_and_response.erb (0.8ms)
Rendered /Users/toptier/.rvm/gems/ruby-1.9.2-p320/gems/actionpack-3.1.8/lib/action_dispatch/middleware/templates/rescues/template_error.erb within rescues/layout (6.7ms)
```

The problem is on questions.rb, specifically the line 

``` ruby
menu :if => lambda{|tabs_renderer|controller.current_ability.can?(:edit, Question)}, :priority => 6
```

This is for conditionally add a resource to the menu, if the user has the ability to edit it. 
If I comment this line it works well.

It worked on 0.4.x versions. 
This is configured in the initializer:   config.current_user_method = :current_admin_user

Thanks
