### ISSUE TITLE
Issue with Ransack 1.8.6

### ISSUE THREAD

**Issue by svoerman** [activeadmin/activeadmin#5333]
Using a bundle update the version of Ransack was increased to 1.8.6 (from 1.8.4). The filter for the title of a model started to fail with the following error:

```undefined method `names_by_decreasing_length' for Ransack::Predicate:Class```

This method has been removed from Ransack 1.8.6 to increase memory performance. Somehow this method is called by ActiveAdmin, though I can't find where and how.

**Comment by svoerman** [comment]
We are using an old version of ActiveAdmin for some reason. Case closed.

**Comment by waqaszafar1** [comment]
I am having the same issue. I am bound to use rails 4.1.0 which only allows activeadmin <= 1.0.0.pre5
My ransack behaving like same for the filters.

`undefined method `names_by_decreasing_length' for Ransack::Predicate:Class`

**Comment by macfanatic** [comment]
Running Rails `5.1.4` with ActiveAdmin `1.0.0` produced this error from me, and upgrading to ActiveAdmin `1.1.0` resolved the issue.

**Comment by danielricecodes** [comment]
Same issue.  Upgrading fixed it.

```ruby
gem 'activeadmin', '~> 1.1.0'
```

then `bundle update activeadmin` FTW.

**Comment by pedrojsn96** [comment]
This update broken my js dependencies :(
Are there another way to solve this?

**Comment by Asterrea** [comment]
Filter on activeadmin gives this error. I tried updating to activeadmin 1.1.0 - the following dependencies broke not sure how to fix yet

`Bundler could not find compatible versions for gem "actionpack":
  In Gemfile:
    active_model_serializers was resolved to 0.10.7, which depends on
      actionpack (< 6, >= 4.1)

    csv_builder was resolved to 2.1.1, which depends on
      actionpack (>= 3.0.0)

    rails (= 4.1.16) was resolved to 4.1.16, which depends on
      actionpack (= 4.1.16)

    activeadmin (~> 1.1.0) was resolved to 1.1.0, which depends on
      ransack (~> 1.3) was resolved to 1.8.9, which depends on
        actionpack (<= 5.1.1, >= 3.0)

    rspec-rails was resolved to 3.8.0, which depends on
      actionpack (>= 3.0)

    simple_form was resolved to 4.0.0, which depends on
      actionpack (> 4)

Bundler could not find compatible versions for gem "activemodel":
  In Gemfile:
    active_model_serializers was resolved to 0.10.7, which depends on
      activemodel (< 6, >= 4.1)

    rails (= 4.1.16) was resolved to 4.1.16, which depends on
      activemodel (= 4.1.16)

    simple_form was resolved to 4.0.0, which depends on
      activemodel (> 4)

Bundler could not find compatible versions for gem "activerecord":
  In Gemfile:
    delayed_job_active_record was resolved to 4.1.3, which depends on
      activerecord (< 5.3, >= 3.0)

    delayed_job_web was resolved to 1.4.3, which depends on
      activerecord (> 3.0.0)

    friendly_id was resolved to 5.2.4, which depends on
      activerecord (>= 4.0.0)

    paper_trail (~> 5.0.1) was resolved to 5.0.1, which depends on
      activerecord (< 6.0, >= 3.0)

    rails (= 4.1.16) was resolved to 4.1.16, which depends on
      activerecord (= 4.1.16)

    activeadmin (~> 1.1.0) was resolved to 1.1.0, which depends on
      ransack (~> 1.3) was resolved to 1.8.9, which depends on
        activerecord (<= 5.1.1, >= 3.0)

Bundler could not find compatible versions for gem "activesupport":
  In Gemfile:
    groupdate was resolved to 3.2.1, which depends on
      activesupport (>= 3)

    jbuilder (~> 1.2) was resolved to 1.5.3, which depends on
      activesupport (>= 3.0.0)

    activeadmin (~> 1.1.0) was resolved to 1.1.0, which depends on
      kaminari (< 2.0, >= 0.15) was resolved to 1.1.1, which depends on
        activesupport (>= 4.1.0)

    paper_trail (~> 5.0.1) was resolved to 5.0.1, which depends on
      activesupport (< 6.0, >= 3.0)

    rails (= 4.1.16) was resolved to 4.1.16, which depends on
      activesupport (= 4.1.16)

    activeadmin (~> 1.1.0) was resolved to 1.1.0, which depends on
      ransack (~> 1.3) was resolved to 1.8.9, which depends on
        activesupport (<= 5.1.1, >= 3.0)

    rspec-rails was resolved to 3.8.0, which depends on
      activesupport (>= 3.0)

Bundler could not find compatible versions for gem "nokogiri":
  In Gemfile:
    cashpinas was resolved to 0.1.0, which depends on
      nokogiri (= 1.7.2)

    paynamics was resolved to 0.1.0, which depends on
      nokogiri

    savon was resolved to 2.11.2, which depends on
      nokogiri (>= 1.4.0)

Bundler could not find compatible versions for gem "rails":
  In Gemfile:
    rails (= 4.1.16)

    apipie-rails was resolved to 0.5.10, which depends on
      rails (>= 4.1)

Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    activeadmin (~> 1.1.0) was resolved to 1.1.0, which depends on
      railties (< 5.2, >= 4.2)

    rails (= 4.1.16) was resolved to 4.1.16, which depends on
      railties (= 4.1.16)

Bundler could not find compatible versions for gem "ransack":
  In Gemfile:
    ransack

    activeadmin (~> 1.1.0) was resolved to 1.1.0, which depends on
      ransack (~> 1.3)
`

**Comment by deivid-rodriguez** [comment]
@Asterrea Activeadmin 1.0.0 or higher does not support the Rails version you're using (4.1.16). You should first upgrade Rails to 4.2 at the very least, and only then attempt to upgrade `activeadmin`. The error message you're getting is big, but the culprit that explains this is this bit:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    activeadmin (~> 1.1.0) was resolved to 1.1.0, which depends on
      railties (< 5.2, >= 4.2)

    rails (= 4.1.16) was resolved to 4.1.16, which depends on
      railties (= 4.1.16)
```

I guess another workaround for you until you can upgrade Rails could be to downgrade ransack back to 1.8.4?

**Comment by omnikron** [comment]
@deivid-rodriguez downgrading to ransack 1.8.4 fixed this issue for me in rails 4.2 + activeadmin 1.0.0.  I would love to update activeadmin instead, but there's an issue with rails 4.2 and jquery that breaks the asset pipeline.

**Comment by deivid-rodriguez** [comment]
@seb-sykio Could you open a new issue with steps to reproduce it? Also, can you reproduce the issue against activeadmin's master?

**Comment by danielricecodes** [comment]
> hi
> I'm still having this issue "exception : undefined method `names_by_decreasing_length' for Ransack::Predicate:Class"
> I'm using ransack (2.1.0) and activeadmin (1.4.0) and rails 5.2.1
> i can't downgrade to ransack 1.8.4 as activeadmin requires ransack >= 1.8.7
> thanks for help

Downgrade to ActiveAdmin 1.3.1.  It works with my Rails 5.2.1 app.  I also have ransack locked to 2.1.0 in that app as well and there are no problems.

**Comment by railslauncher** [comment]
> @deivid-rodriguez downgrading to ransack 1.8.4 fixed this issue for me in rails 4.2 + activeadmin 1.0.0. I would love to update activeadmin instead, but there's an issue with rails 4.2 and jquery that breaks the asset pipeline.

This worked for me. I have explicitly specified the ransack version to `~> 1.8.4`  in Gemfile to fix the issue.

**Comment by dvodvo** [comment]
> This worked for me. I have explicitly specified the ransack version to ~> 1.8.4 in Gemfile to fix the issue.

Dealing with a legacy app... Specifying in Gemfile was insufficient for me. I had to `gem install ransack -v 1.8.4`.  It ran fine on localhost with ruby 2.2.10p489

on a testing VPS the same command fails with:
`nokogiri requires Ruby version >= 2.3.0.`
then  `zeitwerk requires Ruby version >= 2.4.4` which in turn
`activesupport requires Ruby version >= 2.5.0.`

Only way out: install ruby 2.5, then `rbenv local 2.5.8` then `gem install ransack -v 1.8.4`.
Return rbenv to the version required by the app.

**Comment by tilvin** [comment]
If it's still actual problem for someone, this small monkey patch works for me:
```
module ActiveAdmin
  module Filters
    class Humanized
      private

      def current_predicate
        Ransack::Predicate.detect_from_string @body
      end
    end
  end
end
```

Base on Ransack maintainer [discussion](https://github.com/activerecord-hackery/ransack/pull/820#discussion_r160449818)

**Comment by shamimevatix** [comment]
@tilvin . Your reply resolve my issue. Thank you very much.
