### ISSUE TITLE
undefined method type for nil:NilClass

### ISSUE THREAD

**Issue by kashifnaseer** [activeadmin/activeadmin#2937]
In Every show action, I'm getting below mentioned error after updating ActiveAdmin from version 0.6.2 to 0.6.3

ActionView::Template::Error (undefined method `type' for nil:NilClass):
    1: insert_tag renderer_for(:show)
