### ISSUE TITLE
Including comments on a "Show" page via the active_admin_comments helper broke in 2.0.0

### ISSUE THREAD

**Issue by denisahearn** [activeadmin/activeadmin#5768]
After upgrading to ActiveAdmin 2.0.0 from 1.4.3, we noticed that all our "Show" pages started returning a 404 page. Also, all our rspec specs that tested the behavior of our "Show" pages also broke once we upgraded the gem.

We tracked the problem down to the use of the `active_admin_comments` helper. If we remove the call to this helper, then the "Show" pages worked again. 

Digging a bit further, we found this problem in `lib/active_admin/form/active_record/comments/views/active_admin_comments.rb`

```
def build(resource)
  if authorized?(ActiveAdmin::Auth::READ, ActiveAdmin::Comment)
    @resource = resource
    @comments = active_admin_authorization.scope_collection(ActiveAdmin::Comment.find_for_resource_in_namespace(resource, active_admin_namespace.name).includes(:author).page(params[:page]))
    super(title, for: resource)
    build_comments
  end
end
```

The call to `active_admin_authorization.scope_collection` is failing with the following error:

`NameError: undefined local variable or method `active_admin_authorization' for "            <div class=\"comments\"></div>\n":ActiveAdmin::Comments::Views::Comments`

I created a small Rails app that demonstrates this problem, which I have attached to this issue. Note that a brand new Rails app with a vanilla install of ActiveAdmin does not exhibit the problem. It was only after I configured ActiveAdmin to use Pundit for authorization that I was able to reproduce the problem that my team's Rails app experienced once we upgraded to 2.0.0.

The issue gets uncovered because of an override of `ActiveAdmin::ResourceController#authorize!` that we are using so that we can use Pundit's `authorize` method. This is defined at the bottom of `config/initializers/active_admin.rb`. Note that this override works fine with ActiveAdmin 1.4.3.

```
module ActiveAdmin
  class ResourceController
    # this overrides active_admin "authorize!" to use pundit's "authorize"
    def authorize!(permission, resource)
      authorize resource
    end
  end
end
```

Using ActiveAdmin 2.0.0, the use of this override causes the following error:

`ActionView::Template::Error (undefined local variable or method `active_admin_authorization' for "            <div class=\"comments\"></div>\n":ActiveAdmin::Comments::Views::Comments`

Note that we did find a workaround for this issue, by doing the following in the `authorize!` override:

```
module ActiveAdmin
  class ResourceController
    # this overrides active_admin "authorize!" to use pundit's "authorize"
    def authorize!(permission, resource)
      #-----------
      # Workaround to force @active_admin_authorization to be loaded
      active_admin_authorization
      #-----------
      authorize resource
    end
  end
end
```

### Expected behavior

The "Show" pages should work they did in version 1.4.3 of the ActiveAdmin gem, meaning they should render the details for a resource, including the panel with the comments.

### Actual behavior

The "Show" pages are returning a 404 Page Not Found response

### How to reproduce

Run the sample Rails app attached to this issue, go to `http://localhost:3000/admin/posts/1`

[active_admin_test.zip](https://github.com/activeadmin/activeadmin/files/3272843/active_admin_test.zip)

**Comment by deivid-rodriguez** [comment]
This should be fixed in activeadmin 2.1.0, can you give it a try?

**Comment by denisahearn** [comment]
Wow, that was fast. Yes, activeadmin 2.1.0 does indeed fix the issue. I'll remove our workaround. Thanks!

**Comment by deivid-rodriguez** [comment]
No problem, closing!
