### ISSUE TITLE
While building AttributesTable, `is_array?` gives false positives.

### ISSUE THREAD

**Issue by leonelgalan** [activeadmin/activeadmin#4123]
[`is_array?`](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/views/components/attributes_table.rb#L106) gives false positives for objects that are Hashes, wrapped into other clases. This is very common on API wrappers like Stripe. `Stripe::Customer`, for example, is essentially a Hash, but will return false for `!obj.is_a?(Hash)` and doesn't have a `.size` method, like  as required by [`single_record?`](https://github.com/activeadmin/activeadmin/blob/master/lib/active_admin/views/components/attributes_table.rb#L102).

This will cause an "**ActionView::Template::Error**: undefined method `size' for #<Stripe::Customer:0x007f45b5c9d860>" when `obj` is a `Stripe::Customer`

Maybe we should redefined this method as:

```ruby
def is_array?(obj)
  obj.respond_to?(:each) && obj.respond_to?(:size) && obj.respond_to?(:first) && !obj.is_a?(Hash)
end
```

**Comment by seanlinsley** [comment]
The only place that method is used is here:
```ruby
@collection = is_array?(obj) ? obj : [obj]
```

I can't remember why this code was needed. Can't we use `Array.wrap` instead?

**Comment by seanlinsley** [comment]
Looks like it was introduced by #3084. @krainboltgreene can you think of a reason why `Array.wrap` wouldn't work for your case? Unfortunately that PR didn't have any tests.

**Comment by seanlinsley** [comment]
@leonelgalan would you like to open a PR for this?

**Comment by krainboltgreene** [comment]
This is definitely solvable by using `Array[obj]` or `Array.wrap(obj)`.

**Comment by krainboltgreene** [comment]
Donno how I didn't see this, btw @seanlinsley. My bad.

**Comment by seanlinsley** [comment]
no worries :smile:

**Comment by timoschilling** [comment]
closed by #4216
