### ISSUE TITLE
Using symbols with ActiveAdmin.register as :something causes the routes to disappear in version 2.10

### ISSUE THREAD

**Issue by x9sim9** [activeadmin/activeadmin#7728]
### Did you find a bug?

works in <= 2.9.0
ActiveAdmin.register as :something

breaks in >= 2.10.0

### Expected behavior

Should work as before

### Actual behavior

Routes completely dissapear

### How to reproduce

See Above

[our bug report template]: https://github.com/activeadmin/activeadmin/blob/master/tasks/bug_report_template.rb

**Comment by x9sim9** [comment]
This was an absolute nightmare to find the issue in a huge AA project, so while changing them to strings resolves the issue, I hope that as its breaking existing functionality it can either be patched or added to the changelogs between versions.

**Comment by JewelSam** [comment]
Am I right that you mean defining active admin resource like that: `ActiveAdmin.register AdminUser, as: :user`? 
I've checked in 2.9.0, and even rails server can be ran with symbolic "as" option. It fails with error:
```
/Users/username/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/activeadmin-2.9.0/lib/active_admin/resource/naming.rb:7:in `resource_name': 
undefined method `gsub' for :user:Symbol (NoMethodError)

          as = @options[:as].gsub /\\s/, "" if @options[:as]
```
I'm not sure how it worked for you? Maybe it was not 2.9.0 version?
