### ISSUE TITLE
NoMethodError  `undefined method `values' for nil:NilClass`

### ISSUE THREAD

**Issue by dylanjha** [activeadmin/activeadmin#2998]
this happened when I upgraded from 128379bd0af4e79c017d23130922c698f27cd360 to 9ca081f47ab447793afbd0cb2ba1eded68c26f10.  Compare view [here](https://github.com/gregbell/active_admin/compare/128379bd0af4e79c017d23130922c698f27cd360...9ca081f47ab447793afbd0cb2ba1eded68c26f10)

The exception gets thrown when I visit the index page for this resource `ModelName`

this was the line:
`@batch_actions` is nil https://github.com/gregbell/active_admin/blob/master/lib/active_admin/batch_actions/resource_extension.rb#L13

Couldn't not figure out where this bug was coming from.  For this resource all I did was the very basic:

``` ruby
ActiveAdmin.register ModelName do
  menu parent: 'Parent Menu'
end
```

``` ruby
#initializer
config.batch_actions = true
```

When I tried turning off batch actions for this one resource: `ModelName`

``` ruby
ActiveAdmin.register ModelName do
  menu parent: 'Parent Menu'
  config.batch_actions = false
end
```

I got a new exception when starting my server:

``` ruby
undefined method `batch_actions=' for #<ActiveAdmin::Resource:0x007fa96efca188> (NoMethodError)
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p353/bundler/gems/active_admin-9ca081f47ab4/lib/active_admin/dsl.rb:15:in `instance_exec'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p353/bundler/gems/active_admin-9ca081f47ab4/lib/active_admin/dsl.rb:15:in `run_registration_block'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p353/bundler/gems/active_admin-9ca081f47ab4/lib/active_admin/namespace.rb:223:in `parse_registration_block'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p353/bundler/gems/active_admin-9ca081f47ab4/lib/active_admin/namespace.rb:48:in `register'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p353/bundler/gems/active_admin-9ca081f47ab4/lib/active_admin/application.rb:120:in `register'
    from /Users/dylanjhaveri/.rvm/gems/ruby-2.0.0-p353/bundler/gems/active_admin-9ca081f47ab4/lib/active_admin.rb:76:in `register'
```
