### ISSUE TITLE
Rails 4 HABTM filter as: :check_boxes doesn't work

### ISSUE THREAD

**Issue by charredUtensil** [activeadmin/activeadmin#2934]
I have two models with a HABTM relationship in Rails 4, and this:

``` ruby
ActiveAdmin.register MailingList do
  filter :cities, as: :check_boxes, collection: proc { City.all }
end
```

causes this on the index page:

> undefined method `city_ids_in' for #Ransack::Search:0x0000000709a8d8

filter works as: :select perfectly fine

**Comment by mattheworiordan** [comment]
I too am having this issue.

In my example, the issue occurs only with check boxes as well.

My models are:

```ruby
class Incident < ActiveRecord::Base
  enum severity: [ :info, :performance_issues, :service_disruption ]
  has_and_belongs_to_many :services
  accepts_nested_attributes_for :services, allow_destroy: true
end

class Service < ActiveRecord::Base
  enum group: [ :website, :realtime ]
  has_and_belongs_to_many :incidents
end
```

Then in my admin file, the relevant bits are:
```ruby
ActiveAdmin.register Incident do
  permit_params services: [], service_ids: []
  filter :services, as: :check_boxes, collection: [proc { Service.all }]
```

If I change the filter to `filter :services, as: :check_boxes` it works.

The stack trace is as follows:

```
NoMethodError - undefined method `service_ids_in' for #<Ransack::Search:0x007f85f1fc2aa0>:
  ransack (1.6.3) lib/ransack/search.rb:113:in `method_missing'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/inputs/filters/check_boxes_input.rb:12:in `selected_values'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:136:in `checked?'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:126:in `check_box_without_hidden_input'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:171:in `checkbox_input'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:91:in `choice_html'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:80:in `block (5 levels) in to_html'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `capture'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/inputs/filters/check_boxes_input.rb:35:in `choice_wrapping'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:79:in `block (4 levels) in to_html'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:78:in `block (3 levels) in to_html'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `capture'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/inputs/filters/check_boxes_input.rb:30:in `choices_group_wrapping'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:77:in `block (2 levels) in to_html'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  formtastic (3.1.3) lib/formtastic/inputs/base/choices.rb:8:in `choices_wrapping'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:74:in `block in to_html'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `capture'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/inputs/filters/base.rb:12:in `input_wrapping'
  formtastic (3.1.3) lib/formtastic/inputs/check_boxes_input.rb:73:in `to_html'
  formtastic (3.1.3) lib/formtastic/helpers/input_helper.rb:240:in `input'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/filters/forms.rb:14:in `filter'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/filters/forms.rb:62:in `block (2 levels) in active_admin_filters_form_for'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/filters/forms.rb:58:in `block in active_admin_filters_form_for'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `block in capture'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:200:in `with_output_buffer'
  actionview (4.2.0) lib/action_view/helpers/capture_helper.rb:38:in `capture'
  actionview (4.2.0) lib/action_view/helpers/form_helper.rb:444:in `form_for'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/filters/forms.rb:57:in `active_admin_filters_form_for'
  arbre (1.0.3) lib/arbre/element.rb:180:in `method_missing'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/filters/resource_extension.rb:136:in `block in filters_sidebar_section'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/components/sidebar_section.rb:20:in `build_sidebar_content'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/components/sidebar_section.rb:13:in `build'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `sidebar_section'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:126:in `block (2 levels) in build_sidebar'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:125:in `block in build_sidebar'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:124:in `build_sidebar'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:72:in `block in build_page_content'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:70:in `build_page_content'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:48:in `block (2 levels) in build_page'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:14:in `div'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:44:in `block in build_page'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:43:in `build_page'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/views/pages/base.rb:10:in `build'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
  arbre (1.0.3) lib/arbre/context.rb:92:in `with_current_arbre_element'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:26:in `build_tag'
  arbre (1.0.3) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/app/views/active_admin/resource/index.html.arb:2:in `block in ___sers_matthew__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin_ed_fbca_c__a_app_views_active_admin_resource_index_html_arb___3424206693075361665_70106579882940'
  arbre (1.0.3) lib/arbre/context.rb:45:in `initialize'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/app/views/active_admin/resource/index.html.arb:1:in `___sers_matthew__rbenv_versions_______lib_ruby_gems_______bundler_gems_activeadmin_ed_fbca_c__a_app_views_active_admin_resource_index_html_arb___3424206693075361665_70106579882940'
  actionview (4.2.0) lib/action_view/template.rb:145:in `block in render'
  activesupport (4.2.0) lib/active_support/notifications.rb:166:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:333:in `instrument'
  actionview (4.2.0) lib/action_view/template.rb:143:in `render'
  xray-rails (0.1.15) lib/xray/engine.rb:33:in `render_with_xray'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
  actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionview (4.2.0) lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:52:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/template_renderer.rb:14:in `render'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:42:in `render_template'
  actionview (4.2.0) lib/action_view/renderer/renderer.rb:23:in `render'
  actionview (4.2.0) lib/action_view/rendering.rb:100:in `_render_template'
  actionpack (4.2.0) lib/action_controller/metal/streaming.rb:217:in `_render_template'
  actionview (4.2.0) lib/action_view/rendering.rb:83:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:32:in `render_to_body'
  actionpack (4.2.0) lib/action_controller/metal/renderers.rb:37:in `render_to_body'
  actionpack (4.2.0) lib/abstract_controller/rendering.rb:25:in `render'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:16:in `render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block (2 levels) in render'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
  /Users/matthew/.rbenv/versions/2.2.0/lib/ruby/2.2.0/benchmark.rb:303:in `realtime'
  activesupport (4.2.0) lib/active_support/core_ext/benchmark.rb:12:in `ms'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:41:in `block in render'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:84:in `cleanup_view_runtime'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:40:in `render'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:10:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:236:in `default_render'
  responders (2.1.0) lib/action_controller/responder.rb:170:in `to_html'
  responders (2.1.0) lib/responders/flash_responder.rb:107:in `to_html'
  responders (2.1.0) lib/action_controller/responder.rb:163:in `respond'
  responders (2.1.0) lib/action_controller/responder.rb:156:in `call'
  responders (2.1.0) lib/action_controller/respond_with.rb:203:in `respond_with'
  inherited_resources (1.6.0) lib/inherited_resources/actions.rb:7:in `index'
   () Users/matthew/.rbenv/versions/2.2.0/lib/ruby/gems/2.2.0/bundler/gems/activeadmin-ed1fbca8c64a/lib/active_admin/resource_controller/streaming.rb:12:in `index'
  actionpack (4.2.0) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:198:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rendering.rb:10:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
  activesupport (4.2.0) lib/active_support/callbacks.rb:117:in `call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:234:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:169:in `block in halting'
  activesupport (4.2.0) lib/active_support/callbacks.rb:92:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_process_action_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/abstract_controller/callbacks.rb:19:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/rescue.rb:29:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:31:in `block in process_action'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `block in instrument'
  activesupport (4.2.0) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
  activesupport (4.2.0) lib/active_support/notifications.rb:164:in `instrument'
  actionpack (4.2.0) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
  actionpack (4.2.0) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
  activerecord (4.2.0) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
  actionpack (4.2.0) lib/abstract_controller/base.rb:137:in `process'
  actionview (4.2.0) lib/action_view/rendering.rb:30:in `process'
  actionpack (4.2.0) lib/action_controller/metal.rb:195:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
  actionpack (4.2.0) lib/action_controller/metal.rb:236:in `block in action'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:42:in `serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:43:in `block in serve'
  actionpack (4.2.0) lib/action_dispatch/journey/router.rb:30:in `serve'
  actionpack (4.2.0) lib/action_dispatch/routing/route_set.rb:802:in `call'
  xray-rails (0.1.15) lib/xray/middleware.rb:37:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/app_request_handler.rb:13:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/meta_request_handler.rb:13:in `call'
  warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
  warden (1.2.3) lib/warden/manager.rb:34:in `call'
  rack (1.6.0) lib/rack/etag.rb:24:in `call'
  rack (1.6.0) lib/rack/conditionalget.rb:25:in `call'
  rack (1.6.0) lib/rack/head.rb:13:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/flash.rb:260:in `call'
  rack (1.6.0) lib/rack/session/abstract/id.rb:225:in `context'
  rack (1.6.0) lib/rack/session/abstract/id.rb:220:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/cookies.rb:560:in `call'
  activerecord (4.2.0) lib/active_record/query_cache.rb:36:in `call'
  activerecord (4.2.0) lib/active_record/connection_adapters/abstract/connection_pool.rb:647:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
  activesupport (4.2.0) lib/active_support/callbacks.rb:88:in `_run_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:734:in `_run_call_callbacks'
  activesupport (4.2.0) lib/active_support/callbacks.rb:81:in `run_callbacks'
  actionpack (4.2.0) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/reloader.rb:73:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
  rollbar (1.4.4) lib/rollbar/middleware/rails/rollbar.rb:24:in `block in call'
  rollbar (1.4.4) lib/rollbar.rb:774:in `scoped'
  rollbar (1.4.4) lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
  rack-contrib (1.2.0) lib/rack/contrib/response_headers.rb:17:in `call'
  meta_request (0.3.4) lib/meta_request/middlewares/headers.rb:16:in `call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
  better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
  rollbar (1.4.4) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
  actionpack (4.2.0) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
  railties (4.2.0) lib/rails/rack/logger.rb:38:in `call_app'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `block in call'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `block in tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:26:in `tagged'
  activesupport (4.2.0) lib/active_support/tagged_logging.rb:68:in `tagged'
  railties (4.2.0) lib/rails/rack/logger.rb:20:in `call'
  quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
  actionpack (4.2.0) lib/action_dispatch/middleware/request_id.rb:21:in `call'
  rack (1.6.0) lib/rack/methodoverride.rb:22:in `call'
  rack (1.6.0) lib/rack/runtime.rb:18:in `call'
  activesupport (4.2.0) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
  rack (1.6.0) lib/rack/lock.rb:17:in `call'
  actionpack (4.2.0) lib/action_dispatch/middleware/static.rb:113:in `call'
  rack (1.6.0) lib/rack/sendfile.rb:113:in `call'
  railties (4.2.0) lib/rails/engine.rb:518:in `call'
  railties (4.2.0) lib/rails/application.rb:164:in `call'
  railties (4.2.0) lib/rails/railtie.rb:194:in `method_missing'
  rack (1.6.0) lib/rack/deflater.rb:35:in `call'
  rack (1.6.0) lib/rack/content_length.rb:15:in `call'
  thin (1.6.3) lib/thin/connection.rb:86:in `block in pre_process'
  thin (1.6.3) lib/thin/connection.rb:84:in `pre_process'
  thin (1.6.3) lib/thin/connection.rb:53:in `process'
  thin (1.6.3) lib/thin/connection.rb:39:in `receive_data'
  eventmachine (1.0.7) lib/eventmachine.rb:187:in `run'
  thin (1.6.3) lib/thin/backends/base.rb:73:in `start'
  thin (1.6.3) lib/thin/server.rb:162:in `start'
  rack (1.6.0) lib/rack/handler/thin.rb:19:in `run'
  rack (1.6.0) lib/rack/server.rb:286:in `start'
  railties (4.2.0) lib/rails/commands/server.rb:80:in `start'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:80:in `block in server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:75:in `server'
  railties (4.2.0) lib/rails/commands/commands_tasks.rb:39:in `run_command!'
  railties (4.2.0) lib/rails/commands.rb:17:in `<top (required)>'
  bin/rails:8:in `<top (required)>'
  spring (1.3.2) lib/spring/client/rails.rb:27:in `call'
  spring (1.3.2) lib/spring/client/command.rb:7:in `call'
  spring (1.3.2) lib/spring/client.rb:26:in `run'
  spring (1.3.2) bin/spring:48:in `<top (required)>'
  spring (1.3.2) lib/spring/binstub.rb:11:in `<top (required)>'
  /Users/matthew/.rbenv/versions/2.2.0/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
  bin/spring:16:in `<top (required)>'
  ./bin/rails:3:in `<main>'
```

**Comment by deivid-rodriguez** [comment]
@mattheworiordan Is this still happening?

**Comment by mattheworiordan** [comment]
@deivid-rodriguez oops, missed your comment. I will see if I can reproduce.

**Comment by jeffdeville** [comment]
Yes @deivid-rodriguez.  I'm in the process of upgrading from 1.0.0.pre2, where it was working, and can confirm that it now is not working in both 1.0.0, and 1.1.0.

undefined method `tag_ids_in' for Ransack::Search<class: Unit, base: Grouping <combinator: and>>:Ransack::Search
