### ISSUE TITLE
Comments pagination breaks with custom Kaminari page method.

### ISSUE THREAD

**Issue by SirRawlins** [activeadmin/activeadmin#5441]
### Expected behaviour

The paginated comments feature introduced in #5088 should render paginated comments even when using a custom Kaminari 'page_method_name', which may be used to prevent conflicts with will_paginate, [as described in the documentation](https://activeadmin.info/0-installation.html#will_paginate).

### Actual behavior

Trying to render comments since  #5088 raises an exception "undefined method `page' for #<ActiveRecord::Relation []>"

### How to reproduce

Configure a custom Kaminari page method in  `config/initializers/kaminari.rb` like so:

```ruby
Kaminari.configure do |config|
    config.page_method_name = :per_page_kaminari
end
```

Try to render comments with `active_admin_comments` and watch it raise the exception.
