### ISSUE TITLE
Delete button doesn't work in Rails 3.2

### ISSUE THREAD

**Issue by valeriusjames** [activeadmin/activeadmin#1768]
I just incorporated ActiveAdmin 5.0 into a project running Rails 3.2 and it would appear there may be an issue surrounding the Delete button not working, which instead behaves like a the show action (no put/delete).  Initially, any page renders the following error:

TypeError: $._data is not a function
[Break On This Error]   

var events = $._data(document, 'events');

But when I removed the reference of Jquery from active_admin.js, that goes away, but the button still behaves unlike a Delete button should. Perhaps I'm overlooking something, but it has been experienced in the past. See below. Thanks.

Delete button not working
https://github.com/gregbell/active_admin/issues/672

Removed Jquery
https://github.com/gregbell/active_admin/pull/468
