### ISSUE TITLE
activeadmin doesn't work on rails 4.0.+ and 4.1.+ with ruby 1.9.3

### ISSUE THREAD

**Issue by Fivell** [activeadmin/activeadmin#4556]
Hi guys, I'm testing active_admin_import agains multiple rails versions.
since commit  https://github.com/activeadmin/activeadmin/commit/4292aafa33910b705c3076f36e0cb8b2322dbca9
I have broken support for rails 4.0 and 4.1 

```
ActionView::Template::Error:
       undefined method `to_h' for {}:ActionController::Parameters
     # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/activeadmin-1.0.0.pre4/lib/active_admin/batch_actions/resource_extension.rb:58:in `batch_action_path'
     # /home/travis/.rvm/gems/ruby-1.9.3-p551/gems/activeadmin-1.0.0.pre4/lib/active_admin/batch_actions/views/batch_action_form.rb:18:in `build'
```

looks like method to_h was added in rails 4.2

http://apidock.com/rails/ActionController/Parameters/to_h

Can you please comment this? Is active_admin able to support rails < 4.2 ? 

link to travis job with Matrix Ruby 1.9.3 + Rails 4.0.13
https://travis-ci.org/activeadmin-plugins/active_admin_import/jobs/149591932

link to travis job with Matrix Ruby 1.9.3 + Rails  4.1.15
https://travis-ci.org/activeadmin-plugins/active_admin_import/jobs/149591937

**Comment by timoschilling** [comment]
In general we support Rails >= 3.2. But while @seanlinsley has removed Rails 4.0 and 4.1 from the tests, we miss that problem. I will try to get back running tests for 4.0 and 4.1.

**Comment by agentargyle** [comment]
I am running into this problem as well. 

As an aside, I thought I was using Ruby 2.3.0 - running ruby -v tells me I am, as does rvm list. But the default rails index page's "About your application’s environment" link reveals my rails app is somehow still using Ruby 1.9.3. So I am hoping getting that straightened out resolves this for me.
