### ISSUE TITLE
`Page` model issue with v1.4.3

### ISSUE THREAD

**Issue by gsar** [activeadmin/activeadmin#5692]
### Actual behavior

I have a `Page` model for which I have an activeadmin page. The show route for for this contains a panel that shows some related records.  This used to work fine in v1.3.1 but fails in v1.4.3 with:

![image](https://user-images.githubusercontent.com/6981812/53536254-7b642700-3aba-11e9-8ed6-5c590353ab0f.png)

The relevant code looks like this:

``` ruby
ActiveAdmin.register Page do
  index do
    selectable_column
    column :id  
    actions
  end

  show do
    attributes_table do
      row :id 
    end

    panel "Images" do
      table_for(page.images) do
      end
    end
  end
end
```

The reference to `page` in the `panel` seems to be causing the issue.  If I change the `page` to `resource` it works again.

**Comment by dfriquet** [comment]
Hello there,

We just got the same problem upgrading on old app from AA `1.3.1` to `1.4.0`. There is a naming conflict between an `Arbre` method `#page` and the conventionnally-generated `#page` method to retrieved the `Page` instance. A `byebug` in the `show` method reveals that the `page` method is not the one we expected.

```
# AA 1.3.1
(byebug) method(:page).source_location
*** NameError Exception: undefined method `page' for class `#<Class:#<ActiveAdmin::Views::Pages::Show:0x0000556000ee78d8>>'

# AA 1.4.0
(byebug) method(:page).source_location
["/usr/local/bundle/gems/arbre-1.4.0/lib/arbre/element/builder_methods.rb", 13]
```

> If I change the `page` to `resource` it works again.

That did the trick for us too. We'll keep updating our app as far as we can and try to revert to the most-expected `page` version. If it still conflicts in the latest versions, I may send a PR with a word of warning in the documentation.
