### ISSUE TITLE
undefined method `captures' for nil:NilClass

### ISSUE THREAD

**Issue by gravis** [activeadmin/activeadmin#2506]
Hi,

I have an issue after upgrading from 0.6.0 to 0.6.1: 

```
NoMethodError in Admin/users#index
undefined method `captures' for nil:NilClass
```

```
Extracted source (around line #1):

1: insert_tag renderer_for(:index)
```

```

meta_search (1.1.3) lib/meta_search/builder.rb:150:in `matches_attribute_method'
meta_search (1.1.3) lib/meta_search/builder.rb:103:in `respond_to?'
activeadmin (0.6.1) lib/active_admin/inputs/filter_string_input.rb:12:in `to_html'
formtastic (2.2.1) lib/formtastic/helpers/input_helper.rb:240:in `input'
activeadmin (0.6.1) lib/active_admin/form_builder.rb:19:in `block in input'
activeadmin (0.6.1) lib/active_admin/form_builder.rb:177:in `with_new_form_buffer'
activeadmin (0.6.1) lib/active_admin/form_builder.rb:19:in `input'
activeadmin (0.6.1) lib/active_admin/filters/forms.rb:16:in `filter'
activeadmin (0.6.1) lib/active_admin/filters/forms.rb:73:in `block (2 levels) in active_admin_filters_form_for'
activeadmin (0.6.1) lib/active_admin/filters/forms.rb:67:in `each'
activeadmin (0.6.1) lib/active_admin/filters/forms.rb:67:in `block in active_admin_filters_form_for'
actionpack (3.2.14) lib/action_view/helpers/capture_helper.rb:40:in `block in capture'
actionpack (3.2.14) lib/action_view/helpers/capture_helper.rb:187:in `with_output_buffer'
haml (4.0.3) lib/haml/helpers/action_view_xss_mods.rb:5:in `with_output_buffer_with_haml_xss'
actionpack (3.2.14) lib/action_view/helpers/capture_helper.rb:40:in `capture'
haml (4.0.3) lib/haml/helpers/action_view_mods.rb:59:in `capture_with_haml'
actionpack (3.2.14) lib/action_view/helpers/form_helper.rb:378:in `form_for'
haml (4.0.3) lib/haml/helpers/action_view_mods.rb:146:in `form_for_with_haml'
haml (4.0.3) lib/haml/helpers/action_view_xss_mods.rb:28:in `form_for_with_haml_xss'
activeadmin (0.6.1) lib/active_admin/filters/forms.rb:66:in `active_admin_filters_form_for'
arbre (1.0.1) lib/arbre/element.rb:175:in `method_missing'
activeadmin (0.6.1) lib/active_admin/filters/resource_extension.rb:128:in `block in filters_sidebar_section'
activeadmin (0.6.1) lib/active_admin/views/components/sidebar_section.rb:19:in `instance_eval'
activeadmin (0.6.1) lib/active_admin/views/components/sidebar_section.rb:19:in `build_sidebar_content'
activeadmin (0.6.1) lib/active_admin/views/components/sidebar_section.rb:12:in `build'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `sidebar_section'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:122:in `block (2 levels) in build_sidebar'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:121:in `collect'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:121:in `block in build_sidebar'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:120:in `build_sidebar'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:66:in `block in build_page_content'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:64:in `build_page_content'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:47:in `block (2 levels) in build_page'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:31:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:14:in `div'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:44:in `block in build_page'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:49:in `with_current_arbre_element'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:43:in `build_page'
activeadmin (0.6.1) lib/active_admin/views/pages/base.rb:10:in `build'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:30:in `block in build_tag'
arbre (1.0.1) lib/arbre/context.rb:92:in `with_current_arbre_element'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:26:in `build_tag'
arbre (1.0.1) lib/arbre/element/builder_methods.rb:39:in `insert_tag'
activeadmin (0.6.1) app/views/active_admin/resource/index.html.arb:1:in `block in __usr_local_rvm_gems_ruby_______p____xxx_gems_activeadmin_______app_views_active_admin_resource_index_html_arb___3924087578785343284_90928460'
arbre (1.0.1) lib/arbre/context.rb:45:in `instance_eval'
arbre (1.0.1) lib/arbre/context.rb:45:in `initialize'
activeadmin (0.6.1) app/views/active_admin/resource/index.html.arb:1:in `new'
activeadmin (0.6.1) app/views/active_admin/resource/index.html.arb:1:in `__usr_local_rvm_gems_ruby_______p____xxx_gems_activeadmin_______app_views_active_admin_resource_index_html_arb___3924087578785343284_90928460'
actionpack (3.2.14) lib/action_view/template.rb:145:in `block in render'
activesupport (3.2.14) lib/active_support/notifications.rb:125:in `instrument'
actionpack (3.2.14) lib/action_view/template.rb:143:in `render'
actionpack (3.2.14) lib/action_view/renderer/template_renderer.rb:48:in `block (2 levels) in render_template'
actionpack (3.2.14) lib/action_view/renderer/abstract_renderer.rb:38:in `block in instrument'
activesupport (3.2.14) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.14) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.14) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.14) lib/action_view/renderer/abstract_renderer.rb:38:in `instrument'
actionpack (3.2.14) lib/action_view/renderer/template_renderer.rb:47:in `block in render_template'
actionpack (3.2.14) lib/action_view/renderer/template_renderer.rb:55:in `render_with_layout'
actionpack (3.2.14) lib/action_view/renderer/template_renderer.rb:46:in `render_template'
actionpack (3.2.14) lib/action_view/renderer/template_renderer.rb:19:in `render'
actionpack (3.2.14) lib/action_view/renderer/renderer.rb:36:in `render_template'
actionpack (3.2.14) lib/action_view/renderer/renderer.rb:17:in `render'
actionpack (3.2.14) lib/abstract_controller/rendering.rb:110:in `_render_template'
actionpack (3.2.14) lib/action_controller/metal/streaming.rb:225:in `_render_template'
actionpack (3.2.14) lib/abstract_controller/rendering.rb:103:in `render_to_body'
actionpack (3.2.14) lib/action_controller/metal/renderers.rb:28:in `render_to_body'
actionpack (3.2.14) lib/action_controller/metal/compatibility.rb:50:in `render_to_body'
actionpack (3.2.14) lib/abstract_controller/rendering.rb:88:in `render'
actionpack (3.2.14) lib/action_controller/metal/rendering.rb:16:in `render'
actionpack (3.2.14) lib/action_controller/metal/instrumentation.rb:40:in `block (2 levels) in render'
activesupport (3.2.14) lib/active_support/core_ext/benchmark.rb:5:in `block in ms'
/usr/local/rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/benchmark.rb:296:in `realtime'
activesupport (3.2.14) lib/active_support/core_ext/benchmark.rb:5:in `ms'
actionpack (3.2.14) lib/action_controller/metal/instrumentation.rb:40:in `block in render'
actionpack (3.2.14) lib/action_controller/metal/instrumentation.rb:83:in `cleanup_view_runtime'
activerecord (3.2.14) lib/active_record/railties/controller_runtime.rb:24:in `cleanup_view_runtime'
actionpack (3.2.14) lib/action_controller/metal/instrumentation.rb:39:in `render'
activeadmin (0.6.1) lib/active_admin/resource_controller/actions.rb:13:in `block (2 levels) in index'
actionpack (3.2.14) lib/action_controller/metal/responder.rb:230:in `call'
actionpack (3.2.14) lib/action_controller/metal/responder.rb:230:in `default_render'
actionpack (3.2.14) lib/action_controller/metal/responder.rb:160:in `to_html'
responders (1.0.0) lib/responders/flash_responder.rb:104:in `to_html'
actionpack (3.2.14) lib/action_controller/metal/responder.rb:153:in `respond'
actionpack (3.2.14) lib/action_controller/metal/responder.rb:146:in `call'
actionpack (3.2.14) lib/action_controller/metal/mime_responds.rb:239:in `respond_with'
inherited_resources (1.4.1) lib/inherited_resources/actions.rb:7:in `index'
activeadmin (0.6.1) lib/active_admin/resource_controller/actions.rb:11:in `index'
actionpack (3.2.14) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
actionpack (3.2.14) lib/abstract_controller/base.rb:167:in `process_action'
actionpack (3.2.14) lib/action_controller/metal/rendering.rb:10:in `process_action'
actionpack (3.2.14) lib/abstract_controller/callbacks.rb:18:in `block in process_action'
activesupport (3.2.14) lib/active_support/callbacks.rb:480:in `_run__4099743657022628784__process_action__1734070327675007388__callbacks'
activesupport (3.2.14) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.14) lib/active_support/callbacks.rb:385:in `_run_process_action_callbacks'
activesupport (3.2.14) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.14) lib/abstract_controller/callbacks.rb:17:in `process_action'
actionpack (3.2.14) lib/action_controller/metal/rescue.rb:29:in `process_action'
actionpack (3.2.14) lib/action_controller/metal/instrumentation.rb:30:in `block in process_action'
activesupport (3.2.14) lib/active_support/notifications.rb:123:in `block in instrument'
activesupport (3.2.14) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
activesupport (3.2.14) lib/active_support/notifications.rb:123:in `instrument'
actionpack (3.2.14) lib/action_controller/metal/instrumentation.rb:29:in `process_action'
actionpack (3.2.14) lib/action_controller/metal/params_wrapper.rb:207:in `process_action'
activerecord (3.2.14) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
actionpack (3.2.14) lib/abstract_controller/base.rb:121:in `process'
actionpack (3.2.14) lib/abstract_controller/rendering.rb:45:in `process'
actionpack (3.2.14) lib/action_controller/metal.rb:203:in `dispatch'
actionpack (3.2.14) lib/action_controller/metal/rack_delegation.rb:14:in `dispatch'
actionpack (3.2.14) lib/action_controller/metal.rb:246:in `block in action'
actionpack (3.2.14) lib/action_dispatch/routing/route_set.rb:73:in `call'
actionpack (3.2.14) lib/action_dispatch/routing/route_set.rb:73:in `dispatch'
actionpack (3.2.14) lib/action_dispatch/routing/route_set.rb:36:in `call'
journey (1.0.4) lib/journey/router.rb:68:in `block in call'
journey (1.0.4) lib/journey/router.rb:56:in `each'
journey (1.0.4) lib/journey/router.rb:56:in `call'
actionpack (3.2.14) lib/action_dispatch/routing/route_set.rb:608:in `call'
omniauth (1.1.4) lib/omniauth/strategy.rb:184:in `call!'
omniauth (1.1.4) lib/omniauth/strategy.rb:164:in `call'
warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
warden (1.2.3) lib/warden/manager.rb:34:in `catch'
warden (1.2.3) lib/warden/manager.rb:34:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/best_standards_support.rb:17:in `call'
rack (1.4.5) lib/rack/etag.rb:23:in `call'
rack (1.4.5) lib/rack/conditionalget.rb:25:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/head.rb:14:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/params_parser.rb:21:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/flash.rb:242:in `call'
rack (1.4.5) lib/rack/session/abstract/id.rb:210:in `context'
rack (1.4.5) lib/rack/session/abstract/id.rb:205:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/cookies.rb:341:in `call'
activerecord (3.2.14) lib/active_record/query_cache.rb:64:in `call'
activerecord (3.2.14) lib/active_record/connection_adapters/abstract/connection_pool.rb:479:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (3.2.14) lib/active_support/callbacks.rb:405:in `_run__4243653003625550812__call__457831244481306295__callbacks'
activesupport (3.2.14) lib/active_support/callbacks.rb:405:in `__run_callback'
activesupport (3.2.14) lib/active_support/callbacks.rb:385:in `_run_call_callbacks'
activesupport (3.2.14) lib/active_support/callbacks.rb:81:in `run_callbacks'
actionpack (3.2.14) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/reloader.rb:65:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/remote_ip.rb:31:in `call'
airbrake (3.1.12) lib/airbrake/rails/middleware.rb:13:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/debug_exceptions.rb:16:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/show_exceptions.rb:56:in `call'
railties (3.2.14) lib/rails/rack/logger.rb:32:in `call_app'
railties (3.2.14) lib/rails/rack/logger.rb:16:in `block in call'
activesupport (3.2.14) lib/active_support/tagged_logging.rb:22:in `tagged'
railties (3.2.14) lib/rails/rack/logger.rb:16:in `call'
quiet_assets (1.0.2) lib/quiet_assets.rb:18:in `call_with_quiet_assets'
actionpack (3.2.14) lib/action_dispatch/middleware/request_id.rb:22:in `call'
rack (1.4.5) lib/rack/methodoverride.rb:21:in `call'
rack (1.4.5) lib/rack/runtime.rb:17:in `call'
rack (1.4.5) lib/rack/lock.rb:15:in `call'
actionpack (3.2.14) lib/action_dispatch/middleware/static.rb:63:in `call'
airbrake (3.1.12) lib/airbrake/user_informer.rb:16:in `_call'
airbrake (3.1.12) lib/airbrake/user_informer.rb:12:in `call'
railties (3.2.14) lib/rails/engine.rb:484:in `call'
railties (3.2.14) lib/rails/application.rb:231:in `call'
railties (3.2.14) lib/rails/railtie/configurable.rb:30:in `method_missing'
unicorn (4.6.3) lib/unicorn/http_server.rb:552:in `process_client'
unicorn (4.6.3) lib/unicorn/http_server.rb:632:in `worker_loop'
unicorn (4.6.3) lib/unicorn/http_server.rb:500:in `spawn_missing_workers'
unicorn (4.6.3) lib/unicorn/http_server.rb:142:in `start'
unicorn (4.6.3) bin/unicorn_rails:209:in `<top (required)>'
`<main>'
```

This occurs also if I remove everything from the User model.

The attributes are quite common in the model:

```
 => User(id: integer, email: string, encrypted_password: string, reset_password_token: string, reset_password_sent_at: datetime, remember_
created_at: datetime, sign_in_count: integer, current_sign_in_at: datetime, last_sign_in_at: datetime, current_sign_in_ip: string, last_si
gn_in_ip: string, provider: string, uid: string, name: string, phone: string, notifications: string, deleted_at: datetime, cancel_feedback
: text, created_at: datetime, updated_at: datetime, customer_id: string)
```

and I have nothing special in the controller:

``` ruby
ActiveAdmin.register User do

end
```

Any idea?

Thanks
