### ISSUE TITLE
Adding a filter crashes AA, after upgrading from 0.6.6 -> pre2

### ISSUE THREAD

**Issue by DmitryRibalka** [activeadmin/activeadmin#4244]
I just updated AA to pre2 and got this:

`undefined method `map' for #<Proc:0x007ff1d8eb5650>`

if i remove this line everything works ok:

```
filter :user, :as => :select2_multiple, :collection => Proc.new { User.includes(:contact).map { |user| [user.full_name, user.id] } }
```

but i need this filter

**Comment by seanlinsley** [comment]
Can you provide the stack trace for this error?

**Comment by seanlinsley** [comment]
Can you post the definition of the `select2_multiple` filter?

**Comment by DmitryRibalka** [comment]
@seanlinsley
it is a working solution (i spotted that formtastic responds for this and i read the docs about it)
  filter :user_id, :as => :select2_multiple, :collection => Hash[User.includes(:contact).map { |user| [user.full_name, user.id] }]
But, problem is still in there, how to use proc in collection?

**Comment by seanlinsley** [comment]
You shouldn't pass a hash to `:collection` because it will only be executed when the application launches, instead of on each request. Your original code using a proc looked correct.

Could you please supply a stack trace and the definition of the `select2_multiple` filter?

**Comment by DmitryRibalka** [comment]
@seanlinsley slect2 filter wrapper is here
gem 'activeadmin-select2', github: 'dbagaric/activeadmin-select2'
can't provide a stack trace now, need to simulate it.

**Comment by DmitryRibalka** [comment]
I just omited Proc block and it worked.

**Comment by deivid-rodriguez** [comment]
Ok.
