### ISSUE TITLE
Javascript Errors 

### ISSUE THREAD

**Issue by joslinm** [activeadmin/activeadmin#5012]
I can't seem to get the included javascript file to run without any errors. Basically, it seems like jquery UI dialog isn't loaded before dialog.

```
Uncaught TypeError: $.widget is not a function
    at dialog.self-8b9019c….js?body=1:46
    at dialog.self-8b9019c….js?body=1:42
    at dialog.self-8b9019c….js?body=1:44

Uncaught TypeError: Cannot read property 'mouse' of undefined
    at sortable.self-e213a88….js?body=1:37
    at sortable.self-e213a88….js?body=1:33
    at sortable.self-e213a88….js?body=1:35

Uncaught TypeError: $.widget is not a function
    at tabs.self-3c3b343….js?body=1:39
    at tabs.self-3c3b343….js?body=1:35
    at tabs.self-3c3b343….js?body=1:37
```

I tried to resolve this by updating the jquery_ui file (https://github.com/activeadmin/activeadmin/blob/master/app/assets/javascripts/active_admin/jquery_ui.js.erb) by placing widget above dialog, but this just resulted in `base is not a constructor`error.

Have you seen anything like this? I am not sure what is unique about my environment that it's messing with the JS loading. 

Relevant gems:

```
gem "rails", "~> 5.0.0"
gem 'jquery-rails'                                                                                                                                              
gem 'jquery-ui-rails', '~> 6.0.1'
```

*/assets/javascripts/active_admin.js.coffee*:
```#= require active_admin/base```

**Comment by Fivell** [comment]
@joslinm , did you resolve this?

**Comment by javierjulio** [comment]
@joslinm can you help us test out #5052? There we are doing this update for you. In that PR branch we are including the jQuery UI files in the vendor directory for what we use and they are the current, stable, tagged release (jquery-ui-rails v6.0.1). I've tested locally and things work well for me. All our tests pass. Would love to know if that branch fixes this issue you had which it should since we also removed the jquery-ui-rails gem dependency. In v2 we are going to remove jQuery UI and use our own components.

**Comment by joslinm** [comment]
Hey sorry just seeing this. I will try it now

**Comment by javierjulio** [comment]
@joslinm great thanks. It's already in master. If you are using master keep in mind a lot of breaking changes are going in for v2. Make sure that jquery-rails is updated to the latest version. We no longer have jquery-ui-rails as a dependency (we include the JS files directly, slowly transitioning to removing it entirely).

**Comment by joslinm** [comment]
I pulled the master branch (2.0.0.alpha) into my repository and ran with with latest `jquery-rails`. Still receiving the following when I load up dashboard: 

```
dialog.self-8b9019ce473fe212168c4736c9a5a97f8dbca763b4e37be8b441a4dfc0ab9077.js:46 Uncaught TypeError: $.widget is not a function
    at dialog.self-8b9019ce473fe212168c4736c9a5a97f8dbca763b4e37be8b441a4dfc0ab9077.js:46
    at dialog.self-8b9019ce473fe212168c4736c9a5a97f8dbca763b4e37be8b441a4dfc0ab9077.js:42
    at dialog.self-8b9019ce473fe212168c4736c9a5a97f8dbca763b4e37be8b441a4dfc0ab9077.js:44
sortable.self-e213a88a4abe30ca521f12f2df18d123b106bd0e77c07d11737fe0634745be2d.js:37 Uncaught TypeError: Cannot read property 'mouse' of undefined
    at sortable.self-e213a88a4abe30ca521f12f2df18d123b106bd0e77c07d11737fe0634745be2d.js:37
    at sortable.self-e213a88a4abe30ca521f12f2df18d123b106bd0e77c07d11737fe0634745be2d.js:33
    at sortable.self-e213a88a4abe30ca521f12f2df18d123b106bd0e77c07d11737fe0634745be2d.js:35
tabs.self-3c3b343ad2f2b17f895feaf6cb7bd3eb9149fa526a2ce97bf04028b86834df46.js:39 Uncaught TypeError: $.widget is not a function
    at tabs.self-3c3b343ad2f2b17f895feaf6cb7bd3eb9149fa526a2ce97bf04028b86834df46.js:39
    at tabs.self-3c3b343ad2f2b17f895feaf6cb7bd3eb9149fa526a2ce97bf04028b86834df46.js:35
    at tabs.self-3c3b343ad2f2b17f895feaf6cb7bd3eb9149fa526a2ce97bf04028b86834df46.js:37
jquery-ui.self-45333a65ddfe1ff71381b2d58c2d4dd73d131e134a1f523664a08fdf5c15c20a.js:7 Uncaught TypeError: Cannot read property 'dialog' of undefined
    at jquery-ui.self-45333a65ddfe1ff71381b2d58c2d4dd73d131e134a1f523664a08fdf5c15c20a.js:7
jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3861 jQuery.Deferred exception: elems.sortable is not a function TypeError: elems.sortable is not a function
    at init_sortable (http://localhost:3000/assets/active_admin/lib/has_many.self-7d41d46ecadbe8d1a30c2d27ae34265157554968b1ef6ec25fd2e168870b1014.js?body=1:68:9)
    at HTMLDocument.<anonymous> (http://localhost:3000/assets/active_admin/lib/has_many.self-7d41d46ecadbe8d1a30c2d27ae34265157554968b1ef6ec25fd2e168870b1014.js?body=1:62:3)
    at mightThrow (http://localhost:3000/assets/jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3584:29)
    at process (http://localhost:3000/assets/jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3652:12) undefined
jQuery.Deferred.exceptionHook @ jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3861
jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3861 jQuery.Deferred exception: $(...).tabs is not a function TypeError: $(...).tabs is not a function
    at HTMLDocument.onDOMReady (http://localhost:3000/assets/active_admin/initializers/tabs.self-5f37cede19f91addb4997338a3d854ed2441521f5b7ed73493b8e0bdca41e03b.js?body=1:4:43)
    at mightThrow (http://localhost:3000/assets/jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3584:29)
    at process (http://localhost:3000/assets/jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3652:12) undefined
jQuery.Deferred.exceptionHook @ jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3861
jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3870 Uncaught TypeError: elems.sortable is not a function
    at init_sortable (has_many.self-7d41d46ecadbe8d1a30c2d27ae34265157554968b1ef6ec25fd2e168870b1014.js?body=1:68)
    at HTMLDocument.<anonymous> (has_many.self-7d41d46ecadbe8d1a30c2d27ae34265157554968b1ef6ec25fd2e168870b1014.js?body=1:62)
    at mightThrow (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3584)
    at process (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3652)
jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3870 Uncaught TypeError: $(...).tabs is not a function
    at HTMLDocument.onDOMReady (tabs.self-5f37cede19f91addb4997338a3d854ed2441521f5b7ed73493b8e0bdca41e03b.js?body=1:4)
    at mightThrow (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3584)
    at process (jquery3.self-06c43429d1047ce3f355da574d8a9750209971b8b1b8f264f91f5518c5fcc060.js?body=1:3652)
```

**Comment by joslinm** [comment]
I seemed to somewhat resolve it by deleting `jquery-ui` folder in my `app/assets` -- no more errors! 

However, what's going on with dates? Is the calendar going to show? 
![screen shot 2017-08-18 at 2 10 30 pm](https://user-images.githubusercontent.com/178711/29471747-1f16d18a-841f-11e7-8ee0-d5643caea5c7.png)

**Comment by javierjulio** [comment]
Deleting jquery-ui folder? Not sure what's wrong but sounds like you have a pretty custom setup. Can you build a test app with the changes you have to reflect this? Did you also clear out the asset cache? Hard to know what's wrong.

**Comment by joslinm** [comment]
Not really too custom, it's just that I use `require.js` for module loading and when I read docs on jquery-ui w/ `require.js`, just copy the folder over into `app/assets/javascripts`.

I found out how to reproduce this at any rate --

1.) Place `jquery-ui` files into `app/assets/javascripts/jquery-ui`
2.) Load page and see it freak out
3.) Rename `jquery-ui` directory to `jquery-ui-1` (or anything different)
4.) Reload page and see errors clear out 

For my user code, I had to change one module from
`define(['jquery', 'jquery-ui/widgets/autocomplete'`
to
`define(['jquery', 'jquery-ui-1/widgets/autocomplete'`

Do you want me to still build a test app for this?

**Comment by javierjulio** [comment]
Weird, so you are including the files. We do the same now so perhaps its conflicting. I'm not sure there is much we can do. We will be removing jQuery UI entirely with v2, that is my objective. I've started the transition but it'll take some time. Is running on AA v1.0 still an issue for you? I think using AA v1.1+ will not work for you due to us including the jQuery UI assets directly in the vendor folder.

**Comment by joslinm** [comment]
Yes I can but I don't mind changing jquery UI directory. Am I supposed to see calendars for datetimes or am I under the wrong impression? If I'm not, is there anyway to format this to be a bit more pleasing to the eye? Appreciate your help on this.

**Comment by joshmfrankel** [comment]
We just got bit by this issue as well when upgrading to 1.1.0. The problem we ran into was that jquery-ui was already being required within our existing `app/assets/javascripts/active_admin.js`

``` javascript
//= require jquery
//= require jquery_ujs
//= require jquery-ui   // By removing this line we solved our issue
//= require active_admin/base
```

Could we could add a note within the Changelog to indicate the above issue for upgrades? (assuming the above is the correct fix)

**Comment by haariiii** [comment]
Hello how about this issue ?? I still got it ,

**Comment by ianpetzer** [comment]
I just ran into this issue as well when upgrading from 1.0.0-beta to 1.3.0
I'll just record the error message that I was getting to help people find the solution.

```Uncaught TypeError: Cannot read property 'bridge' of undefined```

Which was coming from the line:

```$.widget.bridge('checkboxToggler', ActiveAdmin.CheckboxToggler)```

However the solution from @joshmfrankel fixed it for me. Thanks for posting that!

**Comment by TrishaPatel** [comment]
Is anybody able to solve this problem?
TypeError: $(...).aaDropdownMenu is not a function[Learn More] dropdown-menu.self-5794b6ca26364ce522cb47a8ef050870fda0b886cfeef69ec27ef116900f1984.js:121:32
TypeError: elems.sortable is not a function[Learn More] has_many.self-ece319debdc01ca5096ae8ac6c130ffc0decab382543b4b94e18591375d3d3bb.js:42:5
TypeError: $(...).perPage is not a function[Learn More] per_page.self-ac2a7829e00b21d672b908a9a64b42aef7632ff1dac9a90dda0e779706c71256.js:63:45
TypeError: $(...).tabs is not a function[Learn More]
I am getting this error.
