### ISSUE TITLE
undefined method `task' for Application

### ISSUE THREAD

**Issue by rafamvc** [activeadmin/activeadmin#76]
It seems that the dsl for rake changed and the 3 steps install won't work on rails 3.0.7 with rake 0.9.0 .
To get it working I had to add this code to my rakefile:

``` ruby
# Add this code to rakefile vvv
module ::TestApp
  class Application
    include Rake::DSL
  end
end

module ::RakeFileUtils
  extend Rake::FileUtilsExt
end
# Add this code to rakefile ^^^
TestApp::Application.load_tasks
```

I'm not sure if there is anything we can do to fix this on the active_admin side, but if the rake needs to be rewritten or something I could work on and it and submit a patch. Let me know, I really think it is better when things work out the box, and this is a great gem! :)
