### ISSUE TITLE
upgrading from 0.6.0 to 0.6.1 breaks sidebar `attributes_table_for`

### ISSUE THREAD

**Issue by gingerlime** [activeadmin/activeadmin#2593]
I'm having a problem after upgrading to 0.6.1. We used to have a sidebar that showed non-db resources. Perhaps I built it wrongly in the first place, but it worked before. I used a `Hashie::Mash` to represent a hash in an object-like structure to present it on the sidebar. So it responds to `obj.attr` as well as `obj[:attr]`.

``` ruby
  sidebar "Training Stats", :only => [:show, :edit] do
    training_stats = Hashie::Mash.new({terms_seen: user.stats.terms_seen,
                                       training_sessions: user.training_sessions.count,
                                       points: user.stats.feedback_points,
                                       success_rate: user.stats.get_success_rate,
                                       last_trained: user.stats.last_time_trained })

    attributes_table_for training_stats do
      training_stats.keys.each do |attr|
        row attr
      end
    end
  end
```

Worked fine with 0.6.0, but with 0.6.1 fails with:

```
NoMethodError - undefined method `terms_seen' for ["terms_seen", 0]:Array:
   () root/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/active_admin-0d1952c3e8cd/lib/active_admin/views/components/attributes_table.rb:93:in `find_attr_value'
   () root/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/active_admin-0d1952c3e8cd/lib/active_admin/views/components/attributes_table.rb:83:in `content_for'
   () root/.rbenv/versions/2.0.0-p195/lib/ruby/gems/2.0.0/bundler/gems/active_admin-0d1952c3e8cd/lib/active_admin/views/components/attributes_table.rb:39:in `block (3 levels) in row'
...
```

Any suggestions how to make it work again?
