### ISSUE TITLE
Problem with has_many 'new_record?' function

### ISSUE THREAD

**Issue by benjamin-schaefer** [activeadmin/activeadmin#3857]
Hello,
I work with activeadmin (1.0.0.pre 82fc733) and want to add a 'has_many' relation in my backend. I have 2 models: Participation and Raffle. A participation has many raffles (in model).

If I try the following: 

    form do |f|
      f.inputs do
        f.has_many :raffles, new_record: false do |raffle|
        end
      end 
    end

without any content, it allways throws the following error:

    undefined method `new_record?' for nil:NilClass

Does anybody have an idea what I'm doing wrong?

Regards, Benjamin

**Comment by Fivell** [comment]
@benjamin-schaefer , 
If your ```has_many``` relation doesn't allow destroying, try
```ruby
f.has_many :raffles, new_record: false,  allow_destroy: false do |raffle|
```

**Comment by benjamin-schaefer** [comment]
@Fivell,
unfortunately that doesn't work, still the same error. Any other ideas?

**Comment by Fivell** [comment]
@benjamin-schaefer , please post source of ```Participation``` and ```Raffle``` models
possible that you missed ```accepts_nested_attributes_for``` declaration
 similar problem discussing on stack overflow

http://stackoverflow.com/questions/7206541/activeadmin-with-has-many-problem-undefined-method-new-record

Accepted answer is 
```
accepts_nested_attributes_for :steps
The line is required by formtastic, not active admin. Check https://github.com/justinfrench/formtastic for formtastic documentation
```

**Comment by benjamin-schaefer** [comment]
Ah, okay. Thanks, I'll look for that.
