### ISSUE TITLE
Fails to work with Rails 3.2.0

### ISSUE THREAD

**Issue by rtdp** [activeadmin/activeadmin#933]
I just upgraded my application to rails 3.2.0 from 3.1.3, and I could not start rails server anymore with following error trace  --

```
/home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activeadmin-0.3.4/lib/active_admin/reloader.rb:7:in `updated_at': undefined local variable or method `paths' for #<ActiveAdmin::FileUpdateChecker:0xa7295ac> (NameError)
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/file_update_checker.rb:60:in `initialize'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activeadmin-0.3.4/lib/active_admin/reloader.rb:27:in `new'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activeadmin-0.3.4/lib/active_admin/reloader.rb:27:in `initialize'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activeadmin-0.3.4/lib/active_admin/application.rb:211:in `new'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activeadmin-0.3.4/lib/active_admin/application.rb:211:in `attach_reloader'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activeadmin-0.3.4/lib/active_admin/application.rb:79:in `prepare!'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activeadmin-0.3.4/lib/active_admin.rb:57:in `setup'
    from /home/rtdp/rains/dc/config/initializers/active_admin.rb:1:in `<top (required)>'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:245:in `load'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:245:in `block in load'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:245:in `load'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/engine.rb:588:in `block (2 levels) in <class:Engine>'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/engine.rb:587:in `each'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/engine.rb:587:in `block in <class:Engine>'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/initializable.rb:30:in `instance_exec'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/initializable.rb:30:in `run'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/initializable.rb:55:in `block in run_initializers'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/initializable.rb:54:in `each'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/initializable.rb:54:in `run_initializers'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/application.rb:136:in `initialize!'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/railtie/configurable.rb:30:in `method_missing'
    from /home/rtdp/rains/dc/config/environment.rb:5:in `<top (required)>'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in `require'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in `block in require'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:236:in `load_dependency'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/activesupport-3.2.0/lib/active_support/dependencies.rb:251:in `require'
    from /home/rtdp/rains/dc/config.ru:4:in `block in <main>'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/rack-1.4.0/lib/rack/builder.rb:51:in `instance_eval'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/rack-1.4.0/lib/rack/builder.rb:51:in `initialize'
    from /home/rtdp/rains/dc/config.ru:1:in `new'
    from /home/rtdp/rains/dc/config.ru:1:in `<main>'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/rack-1.4.0/lib/rack/builder.rb:40:in `eval'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/rack-1.4.0/lib/rack/builder.rb:40:in `parse_file'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/rack-1.4.0/lib/rack/server.rb:200:in `app'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/commands/server.rb:46:in `app'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/rack-1.4.0/lib/rack/server.rb:301:in `wrapped_app'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/rack-1.4.0/lib/rack/server.rb:252:in `start'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/commands/server.rb:70:in `start'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/commands.rb:55:in `block in <top (required)>'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/commands.rb:50:in `tap'
    from /home/rtdp/.rvm/gems/ruby-1.9.2-p290@dc/gems/railties-3.2.0/lib/rails/commands.rb:50:in `<top (required)>'
    from script/rails:6:in `require'
    from script/rails:6:in `<main>'
```

Found that earlier I had activesupport 3.1.3, and now i have activesupport 3.2.0
